import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

// Authentic Sri Lankan school-oriented translation dictionary
const translations = {
  en: {
    appName: "SmartSchool LK",
    portalTitle: "School Administration Portal",
    language: "Language",
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    classes: "Classes & Subjects",
    attendance: "Mark Attendance",
    results: "Exam Results",
    notices: "Notice Board",
    alerts: "Emergency Alerts",
    messages: "Parent Messages",
    login: "Log In",
    logout: "Log Out",
    welcome: "Welcome",
    profile: "Profile",
    role: "User Role",
    email: "Email Address",
    password: "Password",
    submit: "Submit",
    save: "Save Changes",
    add: "Add New",
    edit: "Edit",
    delete: "Delete",
    search: "Search...",
    filterClass: "Filter by Class",
    filterDate: "Select Date",
    present: "Present",
    absent: "Absent",
    late: "Late",
    admissionNo: "Admission Number",
    fullName: "Full Name",
    dob: "Date of Birth",
    parentName: "Parent/Guardian",
    phone: "Phone Number",
    address: "Home Address",
    medicalNotes: "Medical & Health Notes",
    actions: "Actions",
    cancel: "Cancel",
    confirmDelete: "Are you sure you want to delete this record?",
    totalStudents: "Total Students",
    totalTeachers: "Total Teachers",
    attendanceRate: "Today's Attendance Rate",
    absentCount: "Absent Today",
    quickActions: "Quick Administrative Actions",
    recentNotices: "Recent School Circulars",
    emergencyAlertButton: "Send Broadcast Emergency Alert",
    enterAlertContent: "Enter emergency alert message details to broadcast via SMS/Email to all parents:",
    alertPlaceholder: "E.g., Due to inclement weather, school will be closed today. Online classes will resume.",
    sendAlert: "Broadcast Alert Now",
    weeklyAttendanceTrend: "Weekly Attendance Attendance Trend (%)",
    assignedClasses: "My Assigned Classes & Subjects",
    pendingAttendance: "Pending Attendance Roll Calls",
    recentAttendance: "Recent Roster Logs",
    resultEntry: "Enter Term Test Marks",
    subject: "Subject",
    examTerm: "Select Exam Term",
    enterMarks: "Enter Marks (0-100)",
    average: "Class Average",
    grade: "Grade",
    classRank: "Class Rank",
    subjectRank: "Subject Rank",
    calculateRanks: "Submit Marks & Calculate Ranks",
    absenceNotifAuto: "Absent students will trigger SMS alerts to parents on submit.",
    childAttendance: "Child's Attendance Statistics",
    childResults: "Child's Progress Report Card",
    childInbox: "School Circulars & Inbox Messages",
    todayStatus: "Arrival Status Today",
    notMarked: "Not Marked Yet",
    subjectName: "Subject Name",
    termMarks: "Term Scores",
    reportCardTitle: "Official Student Progress Report Card",
    printReport: "Print / Save PDF Report",
    gpa: "Term Average / GPA",
    overallGrade: "Overall Grade",
    absentNotificationMsg: "SMS Absence notifications sent to parents.",
    selectChild: "Switch Student Profile",
    sendMessage: "Send Direct Message to Parent",
    messageType: "Message Category",
    messageChannel: "Dispatch Channel",
    messageContent: "Message Body",
    inbox: "Message Drawer",
    sender: "Sender",
    channel: "Channel",
    status: "Status",
    date: "Date"
  },
  si: {
    appName: "SmartSchool LK",
    portalTitle: "පාසල් පරිපාලන ද්වාරය",
    language: "භාෂාව",
    dashboard: "පාලන පුවරුව",
    students: "සිසුන් කළමනාකරණය",
    teachers: "ගුරුවරුන් කළමනාකරණය",
    classes: "පන්ති සහ විෂයන්",
    attendance: "පැමිණීම සලකුණු කිරීම",
    results: "විභාග ප්‍රතිඵල",
    notices: "දැනුම්දීම් පුවරුව",
    alerts: "හදිසි ඇඟවීම්",
    messages: "දෙමාපිය පණිවිඩ",
    login: "ඇතුල් වන්න",
    logout: "පිටවන්න",
    welcome: "ආයුබෝවන්",
    profile: "පැතිකඩ",
    role: "භූමිකාව",
    email: "විද්‍යුත් තැපෑල",
    password: "මුරපදය",
    submit: "ඉදිරිපත් කරන්න",
    save: "සුරකින්න",
    add: "අලුතින් එක් කරන්න",
    edit: "සංස්කරණය",
    delete: "මකා දමන්න",
    search: "සොයන්න...",
    filterClass: "පන්තිය තෝරන්න",
    filterDate: "දිනය තෝරන්න",
    present: "පැමිණ ඇත",
    absent: "පැමිණ නැත",
    late: "ප්‍රමාදයි",
    admissionNo: "ඇතුළත් වීමේ අංකය",
    fullName: "සම්පූර්ණ නම",
    dob: "උපන් දිනය",
    parentName: "දෙමාපියන්/භාරකරු",
    phone: "දුරකථන අංකය",
    address: "ලිපිනය",
    medicalNotes: "සෞඛ්‍යය/වෛද්‍ය සටහන්",
    actions: "ක්‍රියාකාරකම්",
    cancel: "අවලංගු කරන්න",
    confirmDelete: "මෙම වාර්තාව මකා දැමීමට ඔබට විශ්වාසද?",
    totalStudents: "මුළු සිසුන් ගණන",
    totalTeachers: "මුළු ගුරුවරුන් ගණන",
    attendanceRate: "අද දින පැමිණීමේ ප්‍රතිශතය",
    absentCount: "අද පැමිණ නැති සිසුන්",
    quickActions: "ඉක්මන් පරිපාලන ක්‍රියා",
    recentNotices: "නවතම පාසල් චක්‍රලේඛ",
    emergencyAlertButton: "හදිසි විකාශන ඇඟවීම් යවන්න",
    enterAlertContent: "සියලුම දෙමාපියන්ට SMS/විද්‍යුත් තැපෑල මගින් යැවීමට හදිසි පණිවිඩය ඇතුළත් කරන්න:",
    alertPlaceholder: "උදා: අයහපත් කාලගුණය හේතුවෙන් අද දින පාසල වසා තැබේ. සබැඳි පන්ති පැවැත්වේ.",
    sendAlert: "දැන්ම විකාශනය කරන්න",
    weeklyAttendanceTrend: "සතිපතා පැමිණීමේ ප්‍රවණතාවය (%)",
    assignedClasses: "මගේ පන්ති සහ විෂයන්",
    pendingAttendance: "සලකුණු නොකළ පැමිණීම් ලේඛන",
    recentAttendance: "මෑත පැමිණීම් සටහන්",
    resultEntry: "විභාග ලකුණු ඇතුළත් කිරීම",
    subject: "විෂයය",
    examTerm: "විභාග වාරය තෝරන්න",
    enterMarks: "ලකුණු ඇතුළත් කරන්න (0-100)",
    average: "පන්ති සාමාන්‍යය",
    grade: "සාමාර්ථය",
    classRank: "පන්ති මට්ටම",
    subjectRank: "විෂය මට්ටම",
    calculateRanks: "ලකුණු ඇතුළත් කර මට්ටම් ගණනය කරන්න",
    absenceNotifAuto: "නොපැමිණි සිසුන්ගේ දෙමාපියන්ට ස්වයංක්‍රීයව SMS ඇඟවීම් යැවේ.",
    childAttendance: "දරුවාගේ පැමිණීමේ වාර්තා",
    childResults: "දරුවාගේ ප්‍රගති වාර්තා කාඩ්පත",
    childInbox: "පාසල් චක්‍රලේඛ සහ ලැබුණු පණිවිඩ",
    todayStatus: "අද දින පැමිණීමේ තත්ත්වය",
    notMarked: "තවමත් සලකුණු කර නැත",
    subjectName: "විෂය නාමය",
    termMarks: "වාර ලකුණු",
    reportCardTitle: "නිල ශිෂ්‍ය ප්‍රගති වාර්තා කාඩ්පත",
    printReport: "වාර්තාව මුද්‍රණය කරන්න / PDF සුරකින්න",
    gpa: "වාර සාමාන්‍යය ලකුණු",
    overallGrade: "පොදු සාමාර්ථය",
    absentNotificationMsg: "දෙමාපියන් වෙත SMS පණිවිඩ සාර්ථකව යවන ලදී.",
    selectChild: "දරුවාගේ ගිණුම මාරු කරන්න",
    sendMessage: "දෙමාපියන් වෙත පණිවිඩයක් යවන්න",
    messageType: "පණිවිඩ වර්ගය",
    messageChannel: "පණිවිඩ මාධ්‍යය",
    messageContent: "පණිවිඩය",
    inbox: "පණිවිඩ පෙට්ටිය",
    sender: "යවන්නා",
    channel: "මාධ්‍යය",
    status: "තත්ත්වය",
    date: "දිනය"
  },
  ta: {
    appName: "SmartSchool LK",
    portalTitle: "பள்ளி நிர்வாக போர்டல்",
    language: "மொழி",
    dashboard: "கட்டுப்பாட்டு பலகை",
    students: "மாணவர் மேலாண்மை",
    teachers: "ஆசிரியர் மேலாண்மை",
    classes: "வகுப்புகள் & பாடங்கள்",
    attendance: "வருகைப்பதிவு",
    results: "தேர்வு முடிவுகள்",
    notices: "அறிவிப்பு பலகை",
    alerts: "அவசர எச்சரிக்கைகள்",
    messages: "பெற்றோர் செய்திகள்",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    welcome: "வரவேற்கிறோம்",
    profile: "சுயவிவரம்",
    role: "பயனர் பங்கு",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    submit: "சமர்ப்பி",
    save: "மாற்றங்களைச் சேமி",
    add: "புதிதாக சேர்",
    edit: "தொகு",
    delete: "நீக்கு",
    search: "தேடு...",
    filterClass: "வகுப்பினைத் தேர்ந்தெடு",
    filterDate: "தேதியைத் தேர்ந்தெடு",
    present: "வந்தார்",
    absent: "வரவில்லை",
    late: "தாமதம்",
    admissionNo: "சேர்க்கை எண்",
    fullName: "முழு பெயர்",
    dob: "பிறந்த தேதி",
    parentName: "பெற்றோர்/பாதுகாவலர்",
    phone: "தொலைபேசி எண்",
    address: "வீட்டு முகவரி",
    medicalNotes: "மருத்துவக் குறிப்புகள்",
    actions: "நடவடிக்கைகள்",
    cancel: "ரத்து செய்",
    confirmDelete: "இந்த பதிவை நிச்சயமாக நீக்க விரும்புகிறீர்களா?",
    totalStudents: "மொத்த மாணவர்கள்",
    totalTeachers: "மொத்த ஆசிரியர்கள்",
    attendanceRate: "இன்றைய வருகை சதவீதம்",
    absentCount: "இன்று வராதவர்கள்",
    quickActions: "விரைவான நிர்வாக செயல்கள்",
    recentNotices: "சமீபத்திய பள்ளி அறிவிப்புகள்",
    emergencyAlertButton: "அவசர எச்சரிக்கை அனுப்பு",
    enterAlertContent: "அனைத்து பெற்றோருக்கும் SMS/மின்னஞ்சல் மூலம் அனுப்ப அவசர செய்தியை உள்ளிடவும்:",
    alertPlaceholder: "உதாரணம்: மோசமான வானிலை காரணமாக இன்று பள்ளி மூடப்படும். ஆன்லைன் வகுப்புகள் நடைபெறும்.",
    sendAlert: "செய்தியை அனுப்பு",
    weeklyAttendanceTrend: "வாராந்திர வருகை போக்கு (%)",
    assignedClasses: "எனது வகுப்புகள் & பாடங்கள்",
    pendingAttendance: "வருகைப்பதிவு செய்ய வேண்டியவை",
    recentAttendance: "சமீபத்திய வருகைப்பதிவு",
    resultEntry: "தேர்வு மதிப்பெண்கள் உள்ளீடு",
    subject: "பாடம்",
    examTerm: "தேர்வு பருவத்தை தேர்வு செய்க",
    enterMarks: "மதிப்பெண் உள்ளீடு (0-100)",
    average: "வகுப்பு சராசரி",
    grade: "மதிப்பீடு",
    classRank: "வகுப்பு நிலை",
    subjectRank: "பாட நிலை",
    calculateRanks: "மதிப்பெண்களைச் சேமித்து தரவரிசைப்படுத்து",
    absenceNotifAuto: "வராத மாணவர்களின் பெற்றோருக்கு தானாகவே SMS எச்சரிக்கைகள் அனுப்பப்படும்.",
    childAttendance: "பிள்ளையின் வருகை விவரங்கள்",
    childResults: "பிள்ளையின் தேர்வு முடிவு அட்டை",
    childInbox: "பள்ளி அறிவிப்புகள் & இன்பாக்ஸ்",
    todayStatus: "இன்றைய வருகை நிலை",
    notMarked: "இன்னும் பதிவு செய்யப்படவில்லை",
    subjectName: "பாடத்தின் பெயர்",
    termMarks: "பருவ மதிப்பெண்கள்",
    reportCardTitle: "அதிகாரப்பூர்வ மாணவர் முன்னேற்ற அட்டை",
    printReport: "அறிக்கையை அச்சிடுக / PDF சேமி",
    gpa: "பருவ சராசரி மதிப்பெண்கள்",
    overallGrade: "ஒட்டுமொத்த மதிப்பீடு",
    absentNotificationMsg: "பெற்றோருக்கு SMS அனுப்பப்பட்டது.",
    selectChild: "பிள்ளையின் கணக்கை மாற்று",
    sendMessage: "பெற்றோருக்கு செய்தி அனுப்பு",
    messageType: "செய்தி வகை",
    messageChannel: "அனுப்பும் வழிமுறை",
    messageContent: "செய்தி உள்ளடக்கம்",
    inbox: "செய்தி பெட்டி",
    sender: "அனுப்பியவர்",
    channel: "வழிமுறை",
    status: "நிலை",
    date: "தேதி"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('smartschool_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('smartschool_lang', lang);
  }, [lang]);

  // Translate function lookups
  const t = (key) => {
    if (!translations[lang] || !translations[lang][key]) {
      return translations['en'][key] || key;
    }
    return translations[lang][key];
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
